FROM node:22-alpine AS deps

WORKDIR /app

COPY package.json package-lock.json ./
COPY prisma ./prisma
RUN npm ci
RUN npm run prisma:generate

FROM node:22-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .
ARG DATABASE_URL
ARG AUTH_SECRET
ARG APP_READY_BASE_URL
ARG FORGEJO_ADMIN_PASSWORD
ARG FORGEJO_ADMIN_USER
ARG FORGEJO_GIT_URL
ARG FORGEJO_URL
ARG MANAGER_URL
ARG OAUTH_INTERNAL_BASE_URL
ARG PLATFORM_BASE_URL
ARG PLATFORM_DOMAIN
ARG PROJECT_DEV_AGENT_MODEL
ARG PROJECT_PUBLIC_SCHEME
ARG PROJECT_USE_AGENT_MODEL
ARG REDIS_URL
ARG USER_AGENT_MODEL
ENV DATABASE_URL=${DATABASE_URL}
ENV AUTH_SECRET=${AUTH_SECRET}
ENV APP_READY_BASE_URL=${APP_READY_BASE_URL}
ENV FORGEJO_ADMIN_PASSWORD=${FORGEJO_ADMIN_PASSWORD}
ENV FORGEJO_ADMIN_USER=${FORGEJO_ADMIN_USER}
ENV FORGEJO_GIT_URL=${FORGEJO_GIT_URL}
ENV FORGEJO_URL=${FORGEJO_URL}
ENV MANAGER_URL=${MANAGER_URL}
ENV OAUTH_INTERNAL_BASE_URL=${OAUTH_INTERNAL_BASE_URL}
ENV PLATFORM_BASE_URL=${PLATFORM_BASE_URL}
ENV PLATFORM_DOMAIN=${PLATFORM_DOMAIN}
ENV PROJECT_DEV_AGENT_MODEL=${PROJECT_DEV_AGENT_MODEL}
ENV PROJECT_PUBLIC_SCHEME=${PROJECT_PUBLIC_SCHEME}
ENV PROJECT_USE_AGENT_MODEL=${PROJECT_USE_AGENT_MODEL}
ENV REDIS_URL=${REDIS_URL}
ENV USER_AGENT_MODEL=${USER_AGENT_MODEL}
RUN npm run build

FROM node:22-alpine AS runtime

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=80
ENV HOSTNAME=0.0.0.0

COPY package.json package-lock.json ./
COPY prisma ./prisma
RUN npm ci --omit=dev
RUN npm run prisma:generate

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/lib ./lib
COPY --from=builder /app/dist-worker ./dist-worker
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.ts ./next.config.ts

EXPOSE 80

CMD ["sh", "-c", "npm run prisma:push && npm run seed && npm run start"]
